name: Deploy to VPS
on:
  push: { branches: [ main ] }
  workflow_dispatch: {}
concurrency: { group: prod-deploy, cancel-in-progress: true }

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Add VPS host to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H "${{ secrets.VPS_HOST }}" >> ~/.ssh/known_hosts

      - name: Deploy over SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            set -euo pipefail
            cd /home/deploy/app

            git fetch --all --prune
            git checkout main
            git pull --ff-only origin main

            docker compose exec -T -w /var/www/html app php artisan down --secret="${{ secrets.DEPLOY_SECRET }}"

            docker compose exec -T -w /var/www/html app composer install --no-dev --prefer-dist --no-interaction --optimize-autoloader --no-progress || true

            docker compose exec -T -w /var/www/html app php artisan migrate --force

            docker compose exec -T -w /var/www/html app php artisan optimize:clear
            docker compose exec -T -w /var/www/html app php artisan config:cache
            docker compose exec -T -w /var/www/html app php artisan route:cache
            docker compose exec -T -w /var/www/html app php artisan view:cache

            docker compose exec -T -w /var/www/html app php artisan up

      - name: Warmup (optional)
        run: curl -fsS "https://toolshub.jp/${{ secrets.DEPLOY_SECRET }}" || true
